# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sat Aug  8 22:26:31 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((815, 494))
        self.spinWidth = wx.SpinCtrl(self, wx.ID_ANY, "128", min=1, max=65535)
        self.spinHeight = wx.SpinCtrl(self, wx.ID_ANY, "128", min=1, max=65535)
        self.buttonLockSize = wx.ToggleButton(self, wx.ID_ANY, "", style=wx.BU_EXACTFIT)
        self.panelPreviewGradient = wx.Panel(self, wx.ID_ANY)
        self.radioTypeA = wx.RadioButton(self, wx.ID_ANY, "Tipo A", style=wx.RB_GROUP)
        self.radioTypeB = wx.RadioButton(self, wx.ID_ANY, "Tipo B")
        self.radioTypeC = wx.RadioButton(self, wx.ID_ANY, "Tipo C")
        self.spinNumFrames = wx.SpinCtrl(self, wx.ID_ANY, "6", min=1, max=65535)
        self.spinGranularity = wx.SpinCtrl(self, wx.ID_ANY, "0", min=0, max=100)
        self.buttonGenerate = wx.Button(self, wx.ID_ANY, u"¡Generar!")
        self.panelPreview = wx.Panel(self, wx.ID_ANY)
        self.buttonPlayPause = wx.ToggleButton(self, wx.ID_ANY, "", style=wx.BU_EXACTFIT)
        self.sliderPreview = wx.Slider(self, wx.ID_ANY, 0, 0, 10)
        self.spinFps = wx.SpinCtrlDouble(self, wx.ID_ANY, "24.0", min=0.1, max=100.0)
        self.buttonSave = wx.Button(self, wx.ID_ANY, "Guardar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Ventana.__set_properties
        self.SetTitle("Generador de explosiones")
        self.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_WINDOW))
        self.buttonLockSize.SetToolTip(u"Forzar proporción cuadrada")
        self.buttonLockSize.SetBitmap(wx.Bitmap("lock_open.png", wx.BITMAP_TYPE_ANY))
        self.buttonLockSize.SetBitmapPressed(wx.Bitmap("lock.png", wx.BITMAP_TYPE_ANY))
        self.panelPreviewGradient.SetMinSize((-1, 10))
        self.radioTypeA.SetValue(1)
        self.spinNumFrames.SetMinSize((60, 23))
        self.spinGranularity.SetMinSize((60, 23))
        self.buttonGenerate.SetBitmap(wx.Bitmap("lightning.png", wx.BITMAP_TYPE_ANY))
        self.panelPreview.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.buttonPlayPause.SetBitmap(wx.Bitmap("control_play_blue.png", wx.BITMAP_TYPE_ANY))
        self.buttonPlayPause.SetBitmapPressed(wx.Bitmap("control_pause_blue.png", wx.BITMAP_TYPE_ANY))
        self.spinFps.SetMinSize((80, 23))
        self.buttonSave.SetBitmap(wx.Bitmap("diskette.png", wx.BITMAP_TYPE_ANY))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Ventana.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Resultado"), wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Parámetros"), wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(5, 2, 2, 2)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        self.gridGradient = wx.FlexGridSizer(2, 9, 0, 1)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self, wx.ID_ANY, u"Tamaño")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.spinWidth, 0, 0, 0)
        label_7 = wx.StaticText(self, wx.ID_ANY, " x ")
        sizer_2.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.spinHeight, 0, 0, 0)
        label_8 = wx.StaticText(self, wx.ID_ANY, " pixels")
        sizer_2.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add((8, 1), 0, 0, 0)
        sizer_2.Add(self.buttonLockSize, 0, 0, 0)
        grid_sizer_1.Add(sizer_2, 1, wx.ALL | wx.EXPAND, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Gradiente")
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9.Add(self.panelPreviewGradient, 0, wx.EXPAND, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        self.gridGradient.Add((0, 0), 0, 0, 0)
        sizer_9.Add(self.gridGradient, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_9, 1, wx.EXPAND, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Tipo")
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_8.Add(self.radioTypeA, 0, 0, 0)
        sizer_8.Add(self.radioTypeB, 0, 0, 0)
        sizer_8.Add(self.radioTypeC, 0, 0, 0)
        grid_sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, u"Imágenes")
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spinNumFrames, 0, 0, 0)
        label_6 = wx.StaticText(self, wx.ID_ANY, "Granulado")
        grid_sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spinGranularity, 0, 0, 0)
        sizer_6.Add(grid_sizer_1, 0, wx.ALL | wx.EXPAND, 5)
        sizer_6.Add(self.buttonGenerate, 0, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_6, 0, 0, 0)
        sizer_7.Add(self.panelPreview, 1, wx.EXPAND, 0)
        sizer_5.Add(self.buttonPlayPause, 0, 0, 0)
        sizer_5.Add(self.sliderPreview, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_5, 0, wx.EXPAND, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, "Velocidad")
        sizer_4.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.spinFps, 0, 0, 0)
        label_9 = wx.StaticText(self, wx.ID_ANY, "FPS")
        sizer_4.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add((20, 20), 1, 0, 0)
        sizer_4.Add(self.buttonSave, 0, wx.ALL, 0)
        sizer_7.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_7, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class Ventana
